Added two more dependencies to address errors when running test target.
These dependencies were added to ivy.xml:

    <dependency org="org.slf4j" name="slf4j-api" rev="1.6.1"/>
    <dependency org="org.slf4j" name="slf4j-log4j12" rev="1.6.1"/>

to address the errors during the execution of the test target.

[junit] Testcase: testBuildAttributeQueryRequest took 0.01 sec
    [junit] 	Caused an ERROR
    [junit] org/slf4j/LoggerFactory
    [junit] java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
    [junit] 	at
org.opensaml.DefaultBootstrap.<clinit>(DefaultBootstrap.java:36)
    [junit] 	at esg.saml.common.SAMLBuilder.<clinit>(SAMLBuilder.java:171)
    [junit] 	at
esg.saml.attr.service.impl.SAMLAttributeQueryRequestBuilderImplTest.beforeSetup(SAMLAttributeQueryRequestBuilderImplTest.java:49)
    [junit] Caused by: java.lang.ClassNotFoundException:
org.slf4j.LoggerFactory
    [junit] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    [junit] 	at java.security.AccessController.doPrivileged(Native Method)
    [junit] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    [junit] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
    [junit] 	at
sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    [junit] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:248)

Adding the dependencies made this set of errors go away.

-Gavin